# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSLife' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '4.8.0'
  	pod 'SnapKit', '4.2.0'
  	pod 'SDWebImage', '4.4.3'
  	# pod 'SwiftMessages'
  	# pod 'FSCalendar'
  	pod 'MJRefresh', '3.1.15.7'
  	pod 'Charts', '3.2.1'
        pod 'WMPageController', '2.3.0'
        pod 'SwiftyJSON', '4.0.0'
  # Pods for KSLife

  target 'KSLifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KSLifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
